// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.21.12
// source: tuple.proto

package tuplepb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ValueType int32

const (
	ValueType_TYPE_ANY    ValueType = 0
	ValueType_TYPE_BYTES  ValueType = 1
	ValueType_TYPE_STRING ValueType = 2
	ValueType_TYPE_UINT   ValueType = 3
	ValueType_TYPE_INT    ValueType = 4
	ValueType_TYPE_BOOL   ValueType = 5
	ValueType_TYPE_TIME   ValueType = 6
	ValueType_TYPE_FLOAT  ValueType = 7
)

// Enum value maps for ValueType.
var (
	ValueType_name = map[int32]string{
		0: "TYPE_ANY",
		1: "TYPE_BYTES",
		2: "TYPE_STRING",
		3: "TYPE_UINT",
		4: "TYPE_INT",
		5: "TYPE_BOOL",
		6: "TYPE_TIME",
		7: "TYPE_FLOAT",
	}
	ValueType_value = map[string]int32{
		"TYPE_ANY":    0,
		"TYPE_BYTES":  1,
		"TYPE_STRING": 2,
		"TYPE_UINT":   3,
		"TYPE_INT":    4,
		"TYPE_BOOL":   5,
		"TYPE_TIME":   6,
		"TYPE_FLOAT":  7,
	}
)

func (x ValueType) Enum() *ValueType {
	p := new(ValueType)
	*p = x
	return p
}

func (x ValueType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ValueType) Descriptor() protoreflect.EnumDescriptor {
	return file_tuple_proto_enumTypes[0].Descriptor()
}

func (ValueType) Type() protoreflect.EnumType {
	return &file_tuple_proto_enumTypes[0]
}

func (x ValueType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ValueType.Descriptor instead.
func (ValueType) EnumDescriptor() ([]byte, []int) {
	return file_tuple_proto_rawDescGZIP(), []int{0}
}

type Table struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string      `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Key  []*KeyField `protobuf:"bytes,2,rep,name=key,proto3" json:"key,omitempty"`
	Data []*Field    `protobuf:"bytes,3,rep,name=data,proto3" json:"data,omitempty"`
}

func (x *Table) Reset() {
	*x = Table{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tuple_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Table) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Table) ProtoMessage() {}

func (x *Table) ProtoReflect() protoreflect.Message {
	mi := &file_tuple_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Table.ProtoReflect.Descriptor instead.
func (*Table) Descriptor() ([]byte, []int) {
	return file_tuple_proto_rawDescGZIP(), []int{0}
}

func (x *Table) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Table) GetKey() []*KeyField {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *Table) GetData() []*Field {
	if x != nil {
		return x.Data
	}
	return nil
}

type KeyField struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string    `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Type ValueType `protobuf:"varint,2,opt,name=type,proto3,enum=nwca.hidalgo.tuple.ValueType" json:"type,omitempty"`
	Auto bool      `protobuf:"varint,3,opt,name=auto,proto3" json:"auto,omitempty"`
}

func (x *KeyField) Reset() {
	*x = KeyField{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tuple_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *KeyField) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeyField) ProtoMessage() {}

func (x *KeyField) ProtoReflect() protoreflect.Message {
	mi := &file_tuple_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeyField.ProtoReflect.Descriptor instead.
func (*KeyField) Descriptor() ([]byte, []int) {
	return file_tuple_proto_rawDescGZIP(), []int{1}
}

func (x *KeyField) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *KeyField) GetType() ValueType {
	if x != nil {
		return x.Type
	}
	return ValueType_TYPE_ANY
}

func (x *KeyField) GetAuto() bool {
	if x != nil {
		return x.Auto
	}
	return false
}

type Field struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string    `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Type ValueType `protobuf:"varint,2,opt,name=type,proto3,enum=nwca.hidalgo.tuple.ValueType" json:"type,omitempty"`
}

func (x *Field) Reset() {
	*x = Field{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tuple_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Field) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Field) ProtoMessage() {}

func (x *Field) ProtoReflect() protoreflect.Message {
	mi := &file_tuple_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Field.ProtoReflect.Descriptor instead.
func (*Field) Descriptor() ([]byte, []int) {
	return file_tuple_proto_rawDescGZIP(), []int{2}
}

func (x *Field) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Field) GetType() ValueType {
	if x != nil {
		return x.Type
	}
	return ValueType_TYPE_ANY
}

var File_tuple_proto protoreflect.FileDescriptor

var file_tuple_proto_rawDesc = []byte{
	0x0a, 0x0b, 0x74, 0x75, 0x70, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x12, 0x6e,
	0x77, 0x63, 0x61, 0x2e, 0x68, 0x69, 0x64, 0x61, 0x6c, 0x67, 0x6f, 0x2e, 0x74, 0x75, 0x70, 0x6c,
	0x65, 0x22, 0x7a, 0x0a, 0x05, 0x54, 0x61, 0x62, 0x6c, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x2e,
	0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x6e, 0x77,
	0x63, 0x61, 0x2e, 0x68, 0x69, 0x64, 0x61, 0x6c, 0x67, 0x6f, 0x2e, 0x74, 0x75, 0x70, 0x6c, 0x65,
	0x2e, 0x4b, 0x65, 0x79, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x2d,
	0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x6e,
	0x77, 0x63, 0x61, 0x2e, 0x68, 0x69, 0x64, 0x61, 0x6c, 0x67, 0x6f, 0x2e, 0x74, 0x75, 0x70, 0x6c,
	0x65, 0x2e, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x65, 0x0a,
	0x08, 0x4b, 0x65, 0x79, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x31, 0x0a,
	0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1d, 0x2e, 0x6e, 0x77,
	0x63, 0x61, 0x2e, 0x68, 0x69, 0x64, 0x61, 0x6c, 0x67, 0x6f, 0x2e, 0x74, 0x75, 0x70, 0x6c, 0x65,
	0x2e, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x54, 0x79, 0x70, 0x65, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65,
	0x12, 0x12, 0x0a, 0x04, 0x61, 0x75, 0x74, 0x6f, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x04,
	0x61, 0x75, 0x74, 0x6f, 0x22, 0x4e, 0x0a, 0x05, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x12, 0x12, 0x0a,
	0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x12, 0x31, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32,
	0x1d, 0x2e, 0x6e, 0x77, 0x63, 0x61, 0x2e, 0x68, 0x69, 0x64, 0x61, 0x6c, 0x67, 0x6f, 0x2e, 0x74,
	0x75, 0x70, 0x6c, 0x65, 0x2e, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x54, 0x79, 0x70, 0x65, 0x52, 0x04,
	0x74, 0x79, 0x70, 0x65, 0x2a, 0x85, 0x01, 0x0a, 0x09, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x54, 0x79,
	0x70, 0x65, 0x12, 0x0c, 0x0a, 0x08, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x41, 0x4e, 0x59, 0x10, 0x00,
	0x12, 0x0e, 0x0a, 0x0a, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x42, 0x59, 0x54, 0x45, 0x53, 0x10, 0x01,
	0x12, 0x0f, 0x0a, 0x0b, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x53, 0x54, 0x52, 0x49, 0x4e, 0x47, 0x10,
	0x02, 0x12, 0x0d, 0x0a, 0x09, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x55, 0x49, 0x4e, 0x54, 0x10, 0x03,
	0x12, 0x0c, 0x0a, 0x08, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x49, 0x4e, 0x54, 0x10, 0x04, 0x12, 0x0d,
	0x0a, 0x09, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x42, 0x4f, 0x4f, 0x4c, 0x10, 0x05, 0x12, 0x0d, 0x0a,
	0x09, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x54, 0x49, 0x4d, 0x45, 0x10, 0x06, 0x12, 0x0e, 0x0a, 0x0a,
	0x54, 0x59, 0x50, 0x45, 0x5f, 0x46, 0x4c, 0x4f, 0x41, 0x54, 0x10, 0x07, 0x42, 0x2e, 0x5a, 0x2c,
	0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x64, 0x75, 0x63, 0x65, 0x73,
	0x6f, 0x66, 0x74, 0x2f, 0x63, 0x61, 0x79, 0x6c, 0x65, 0x79, 0x2f, 0x64, 0x61, 0x6c, 0x2f, 0x74,
	0x75, 0x70, 0x6c, 0x65, 0x2f, 0x74, 0x75, 0x70, 0x6c, 0x65, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_tuple_proto_rawDescOnce sync.Once
	file_tuple_proto_rawDescData = file_tuple_proto_rawDesc
)

func file_tuple_proto_rawDescGZIP() []byte {
	file_tuple_proto_rawDescOnce.Do(func() {
		file_tuple_proto_rawDescData = protoimpl.X.CompressGZIP(file_tuple_proto_rawDescData)
	})
	return file_tuple_proto_rawDescData
}

var file_tuple_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_tuple_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_tuple_proto_goTypes = []interface{}{
	(ValueType)(0),   // 0: nwca.hidalgo.tuple.ValueType
	(*Table)(nil),    // 1: nwca.hidalgo.tuple.Table
	(*KeyField)(nil), // 2: nwca.hidalgo.tuple.KeyField
	(*Field)(nil),    // 3: nwca.hidalgo.tuple.Field
}
var file_tuple_proto_depIdxs = []int32{
	2, // 0: nwca.hidalgo.tuple.Table.key:type_name -> nwca.hidalgo.tuple.KeyField
	3, // 1: nwca.hidalgo.tuple.Table.data:type_name -> nwca.hidalgo.tuple.Field
	0, // 2: nwca.hidalgo.tuple.KeyField.type:type_name -> nwca.hidalgo.tuple.ValueType
	0, // 3: nwca.hidalgo.tuple.Field.type:type_name -> nwca.hidalgo.tuple.ValueType
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_tuple_proto_init() }
func file_tuple_proto_init() {
	if File_tuple_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_tuple_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Table); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tuple_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*KeyField); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tuple_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Field); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_tuple_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_tuple_proto_goTypes,
		DependencyIndexes: file_tuple_proto_depIdxs,
		EnumInfos:         file_tuple_proto_enumTypes,
		MessageInfos:      file_tuple_proto_msgTypes,
	}.Build()
	File_tuple_proto = out.File
	file_tuple_proto_rawDesc = nil
	file_tuple_proto_goTypes = nil
	file_tuple_proto_depIdxs = nil
}
